[package]
name = "kubert"
version = "0.2.0"
edition = "2021"
license = "Apache-2.0"
description = "Kubernetes runtime helpers. Based on kube-rs."
repository = "https://github.com/olix0r/kubert"

[features]
default = []
client = ["kube/client"]
client-native-tls = ["kube/native-tls"]
client-rustls-tls = ["kube/rustls-tls"]
kube-derive = ["kube/derive"]
kube-runtime = ["kube/runtime"]
# TODO controller = ["client", "kube/runtime"]
log = ["tracing-subscriber"]
# TODO runtime = ["clap", "drain", "log", "tokio/signal"]
webhook = [
    "hyper",
    "hyper/http1",
    "hyper/http2",
    "hyper/runtime",
    "hyper/server",
    "kube/admission",
    "rustls-pemfile",
    "tokio/fs",
    "tokio-rustls",
    "tower-service",
]
v1_20 = ["k8s-openapi/v1_20"]
v1_21 = ["k8s-openapi/v1_21"]
v1_22 = ["k8s-openapi/v1_22"]
v1_23 = ["k8s-openapi/v1_23"]

[dependencies]
#drain = { version = "0.1.0", optional = true, default-features = false }
hyper = { version = "0.14.0", optional = true, default-features = false }
k8s-openapi = { version = "0.14", default-features = false }
kube = { version = "0.69.1", default-features = false }
rustls = { version = "0.20", optional = true, default-features = false }
rustls-pemfile = { version = "0.3", optional = true }
thiserror = "1.0.0"
tokio = "1.6"
tokio-rustls = { version = "0.23", optional = true, default-features = false }
tower-service = { version = "0.3", optional = true }
tracing = "0.1"

[dependencies.clap]
version = "3.0.0"
optional = true
default-features = false
features = ["derive", "env", "std"]

[dependencies.tracing-subscriber]
version = "0.3"
optional = true
default-features = false
features = [
    "env-filter",
    "fmt",
    "json",
    "smallvec",
    "tracing-log",
]
